### ISSUE TITLE
Add mlat client to image

### ISSUE THREAD

**Issue by hakan42** [ShoGinn/radarbox24#1]
The radarbox24 web site asks for an mlat-client to be installed. from the request popup:

```
MLAT inactive - See instructions

In order to activate MLAT in your Raspberry Pi or similar device, please enter the following commands, which will install the latest version of rbfeeder and the MLAT client software:

1. sudo bash -c "$(wget -O - http://apt.rb24.com/inst_rbfeeder.sh)"
2. sudo apt-get install mlat-client -y
3. reboot

After performing the steps above, please set the exact location and height of your antenna.
```

Would be nice if that client could be installed and the environment variables for the location (as used in the other docker images) passed into this image

**Comment by ShoGinn** [comment]
sounds good! I'll check out how to implement.

**Comment by ShoGinn** [comment]
So adding this to the image has proven to be a bit troublesome ;) I want to keep each docker as a single item, since the Radar Box Client doesn't call MLAT on its own I just enabled some features to my existing mlat client.

Check out https://github.com/shoginn/adsbexchange-mlat

you just add your station number and the mlat servers and it works!
